import type { VisualizerShape, IVisualShapeConfig } from '../types';
import type { BackgroundAtmosphere } from '../types/audio';

/**
 * Centralized Visualizer Presets Configuration
 * Extensible configuration dictionary for all 3D geometries and shader modes.
 */
export const VISUAL_SHAPE_PRESETS: Record<VisualizerShape, IVisualShapeConfig> = {
  sphere: {
    id: 'sphere',
    name: 'Esfera Cúbica Cuántica',
    description: 'Nube esférica de partículas con deformación armónica esférica de 4 octavas',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.4,
    colorDistribution: 'frequency',
    deformationAlgorithm: 'harmonic',
  },
  rings: {
    id: 'rings',
    name: 'Anillos Orbitales de Saturno',
    description: '5 anillos concéntricos con satélites reactivos a los armónicos agudos',
    baseRadius: 1.15,
    pointSize: 4.8,
    baseSpeed: 1.1,
    bassReactivity: 1.6,
    colorDistribution: 'concentric',
    deformationAlgorithm: 'orbital',
  },
  spikes: {
    id: 'spikes',
    name: 'Corona de Picos FFT',
    description: 'Estructura cristalina con agujas que se disparan en los transitorios de percusión',
    baseRadius: 0.95,
    pointSize: 4.0,
    baseSpeed: 0.6,
    bassReactivity: 1.9,
    colorDistribution: 'radial',
    deformationAlgorithm: 'spikes',
  },
  cloud: {
    id: 'cloud',
    name: 'Nébula Cuántica Turbulenta',
    description: 'Partículas flotantes con ruido Perlin 3D y dispersión por frecuencias medias',
    baseRadius: 1.25,
    pointSize: 3.6,
    baseSpeed: 0.45,
    bassReactivity: 1.2,
    colorDistribution: 'uniform',
    deformationAlgorithm: 'turbulent',
  },
  torus: {
    id: 'torus',
    name: 'Toroide Magnético',
    description: 'Dona electromagnética en rotación dual con vórtice gravitacional de bajos',
    baseRadius: 1.1,
    pointSize: 4.5,
    baseSpeed: 1.2,
    bassReactivity: 1.5,
    colorDistribution: 'concentric',
    deformationAlgorithm: 'toroidal',
  },
  wave: {
    id: 'wave',
    name: 'Océano de Terreno Sintético',
    description: 'Malla tridimensional ondulante inspirada en sintetizadores modulares retro',
    baseRadius: 1.3,
    pointSize: 3.8,
    baseSpeed: 0.9,
    bassReactivity: 1.7,
    colorDistribution: 'frequency',
    deformationAlgorithm: 'harmonic',
  },
  kaleidoscope: {
    id: 'kaleidoscope',
    name: 'Caleidoscopio Radial',
    description: 'Simetría octa-radial con prismas de difracción rotatorios sensibles a armónicos agudos',
    baseRadius: 1.15,
    pointSize: 4.4,
    baseSpeed: 1.0,
    bassReactivity: 1.5,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  vortex: {
    id: 'vortex',
    name: 'Vórtex Hipnótico Gravitacional',
    description: 'Espirales dobles de luz cuántica succionadas hacia el vacío al compás del bombo',
    baseRadius: 1.2,
    pointSize: 4.2,
    baseSpeed: 1.4,
    bassReactivity: 1.8,
    colorDistribution: 'concentric',
    deformationAlgorithm: 'toroidal',
  },
  fractal: {
    id: 'fractal',
    name: 'Flor Fractal Sagrada',
    description: 'Mándala de geometría fractal con pétalos poligonales que respiran con los graves',
    baseRadius: 1.1,
    pointSize: 4.0,
    baseSpeed: 0.7,
    bassReactivity: 1.6,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  nebula: {
    id: 'nebula',
    name: 'Nebulosa / Aurora Líquida',
    description: 'Estelas de gas cósmico cromático con flujo turbulento y dispersión atmosférica',
    baseRadius: 1.3,
    pointSize: 3.8,
    baseSpeed: 0.5,
    bassReactivity: 1.4,
    colorDistribution: 'uniform',
    deformationAlgorithm: 'turbulent',
  },
  bars: {
    id: 'bars',
    name: 'Barras Radiales Spectrum Pro',
    description: 'Ecualizador circular de 64 bandas con decaimiento de picos estilo consola de audio DJ',
    baseRadius: 1.0,
    pointSize: 4.6,
    baseSpeed: 0.8,
    bassReactivity: 1.9,
    colorDistribution: 'frequency',
    deformationAlgorithm: 'spikes',
  },
  laser: {
    id: 'laser',
    name: 'Rayos Láser Strobe',
    description: 'Haces cinéticos que se disparan en los transitorios de percusión y caja',
    baseRadius: 1.05,
    pointSize: 4.8,
    baseSpeed: 1.2,
    bassReactivity: 2.0,
    colorDistribution: 'radial',
    deformationAlgorithm: 'spikes',
  },
  icosahedron: {
    id: 'icosahedron',
    name: 'Icosaedro Sagrado',
    description: 'Geometría sagrada de 20 caras con vértices pulsantes al ritmo del compás',
    baseRadius: 1.05,
    pointSize: 5.0,
    baseSpeed: 0.75,
    bassReactivity: 1.5,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  octahedron: {
    id: 'octahedron',
    name: 'Octaedro de Diamante Neón',
    description: 'Estructura bipiramidal reflectante con facetas de difracción espectral',
    baseRadius: 1.0,
    pointSize: 4.6,
    baseSpeed: 0.85,
    bassReactivity: 1.6,
    colorDistribution: 'radial',
    deformationAlgorithm: 'spikes',
  },
  cat_ears: {
    id: 'cat_ears',
    name: 'Cresta Dual Paramétrica',
    description: 'Estructura simétrica paramétrica con líneas ultrafinas hairline, rebote elástico Kick y capas Moiré',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  fox_ears: {
    id: 'fox_ears',
    name: 'Agujas Vectoriales',
    description: 'Picos esbeltos convergentes con líneas hairline y micro-nodos radiantes',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  cyber_horns: {
    id: 'cyber_horns',
    name: 'Arcos Hiperbólicos',
    description: 'Arcos curvados simétricos ascendentes con tensión polar y destellos en los vértices',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  valkyrie_wings: {
    id: 'valkyrie_wings',
    name: 'Aletas Aerodinámicas',
    description: 'Aletas laterales simétricas en los flancos con cresta triple y efecto Moiré',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  laser_crown: {
    id: 'laser_crown',
    name: 'Corona Armónica',
    description: 'Diadema geométrica de 4 crestas superiores con precisión matemática',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  dual_crest: {
    id: 'dual_crest',
    name: 'Cresta Dual visionOS',
    description: '2 crestas afiladas simétricas en ángulo cónico con trazo hairline de 1.0px',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  vector_spires: {
    id: 'vector_spires',
    name: 'Agujas Vectoriales',
    description: 'Picos esbeltos de alta tensión polar con micro-nodos radiantes en ápices',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  pulse_antennas: {
    id: 'pulse_antennas',
    name: 'Antenas de Pulso',
    description: 'Doble contorno armónico polar con resonancia de frecuencias medias',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  aero_fins: {
    id: 'aero_fins',
    name: 'Aletas Aerodinámicas',
    description: 'Aletas laterales escalonadas en los flancos con curvatura tangencial',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  apex_prism: {
    id: 'apex_prism',
    name: 'Prisma de Ápice',
    description: 'Crestas triangulares puras inspiradas en aristas de difracción óptica',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  harmonic_crown: {
    id: 'harmonic_crown',
    name: 'Corona Armónica',
    description: 'Crestas cuádruples en cruz simétrica de 90 grados con halo transparente',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  hyperbolic_arcs: {
    id: 'hyperbolic_arcs',
    name: 'Arcos Hiperbólicos',
    description: 'Arcos de barrido polar con deflexión tangencial y tensión de resorte',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  laser_needles: {
    id: 'laser_needles',
    name: 'Agujas Láser Hairline',
    description: 'Agujas radiales ultrafinas de 0.75px con micro-destellos de percusión',
    baseRadius: 1.0,
    pointSize: 4.2,
    baseSpeed: 0.8,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  wave_peaks: {
    id: 'wave_peaks',
    name: 'Halo de Ondas Reactivas',
    description: 'Halo orbital con picos ondulantes que viajan con el ritmo y se expanden con el kick',
    baseRadius: 1.15,
    pointSize: 3.6,
    baseSpeed: 1.2,
    bassReactivity: 1.7,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  cyber_hexagon: {
    id: 'cyber_hexagon',
    name: 'Hexágono Cyber',
    description: 'Polígono hexagonal con cada uno de los 6 lados reactivo a su propia banda FFT',
    baseRadius: 1.05,
    pointSize: 3.2,
    baseSpeed: 0.7,
    bassReactivity: 1.9,
    colorDistribution: 'frequency',
    deformationAlgorithm: 'harmonic',
  },
  octagram_star: {
    id: 'octagram_star',
    name: 'Estrella 8 Puntas',
    description: 'Estrella de 8 puntas con alternancia sinusoidal interior/exterior reactiva',
    baseRadius: 1.10,
    pointSize: 3.8,
    baseSpeed: 0.9,
    bassReactivity: 2.0,
    colorDistribution: 'frequency',
    deformationAlgorithm: 'harmonic',
  },
  phoenix_wings: {
    id: 'phoenix_wings',
    name: 'Alas Fénix',
    description: 'Perfil alar Joukowski asimétrico: ala superior abre con mids, inferior con bajos',
    baseRadius: 1.08,
    pointSize: 3.4,
    baseSpeed: 1.0,
    bassReactivity: 1.8,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  quantum_gyro: {
    id: 'quantum_gyro',
    name: 'Giroscopio Cuántico',
    description: 'Lissajous polar sin(3θ)·cos(2θ): 3 lóbulos giratorios con interferencia Moiré',
    baseRadius: 1.12,
    pointSize: 3.6,
    baseSpeed: 1.1,
    bassReactivity: 1.85,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  lotus_mandala: {
    id: 'lotus_mandala',
    name: 'Mandala Loto',
    description: 'Curva rosa polar k=5 (10 pétalos): se expanden con bajos, rotan con mids',
    baseRadius: 1.10,
    pointSize: 3.0,
    baseSpeed: 0.6,
    bassReactivity: 2.1,
    colorDistribution: 'radial',
    deformationAlgorithm: 'harmonic',
  },
  radar_heartbeat: {
    id: 'radar_heartbeat',
    name: 'Radar EKG',
    description: 'Barrido de radar con complejo QRS gaussiano que late al ritmo de los bajos',
    baseRadius: 1.0,
    pointSize: 2.8,
    baseSpeed: 1.6,
    bassReactivity: 2.2,
    colorDistribution: 'frequency',
    deformationAlgorithm: 'harmonic',
  },
};

export const getVisualShapeConfig = (shape: VisualizerShape): IVisualShapeConfig => {
  return VISUAL_SHAPE_PRESETS[shape] || VISUAL_SHAPE_PRESETS.sphere;
};

export interface EffectOption {
  id: VisualizerShape;
  name: string;
  desc: string;
  tag: string;
  category: string;
}

/**
 * Catálogo exclusivo de Geometrías 3D para la Esfera (WebGL / Three.js)
 */
export const SPHERE_3D_GEOMETRIES: EffectOption[] = [
  {
    id: 'sphere',
    name: 'Esfera Fibonacci',
    desc: 'Esfera cristalina áurea con deformación armónica esférica de 4 octavas.',
    tag: 'FIBONACCI 3D',
    category: 'Esferas & Enjambres',
  },
  {
    id: 'rings',
    name: 'Anillos Orbitales de Saturno',
    desc: '5 anillos orbitales toroides concéntricos con inclinación espacial y oscilación.',
    tag: 'ORBITAL 3D',
    category: 'Anillos & Órbitas',
  },
  {
    id: 'spikes',
    name: 'Corona de Picos FFT',
    desc: 'Geometría erizo 3D con agujas que se disparan en transitorios de percusión.',
    tag: 'RADIAL 3D',
    category: 'Picos & Frecuencias',
  },
  {
    id: 'cloud',
    name: 'Nube Cuántica de Partículas',
    desc: 'Enjambre browniano tridimensional con dispersión espacial continua.',
    tag: 'ENJAMBRE 3D',
    category: 'Esferas & Enjambres',
  },
  {
    id: 'torus',
    name: 'Toroide Cuántico 3D',
    desc: 'Dona electromagnética en rotación dual y deformación gravitacional.',
    tag: 'TOROIDE 3D',
    category: 'Anillos & Órbitas',
  },
  {
    id: 'wave',
    name: 'Océano de Ondas Sinusoidales',
    desc: 'Malla de terreno tridimensional con oleaje dinámico de frecuencias.',
    tag: 'TERRENO 3D',
    category: 'Superficies & Mallas',
  },
  {
    id: 'icosahedron',
    name: 'Icosaedro Sagrado',
    desc: 'Poliedro cristalino de 20 facetas con vértices pulsantes.',
    tag: 'CRISTAL 3D',
    category: 'Poliedros Cristalinos',
  },
  {
    id: 'octahedron',
    name: 'Octaedro Cuántico',
    desc: 'Diamante bipiramidal reflectante con simetría de 8 facetas nítidas.',
    tag: 'DIAMANTE 3D',
    category: 'Poliedros Cristalinos',
  },
];

/**
 * Catálogo exclusivo de Efectos Cinéticos 2D para Rainbow Void (Canvas 2D)
 * Diseños abstractos de Minimalismo Sagrado basados en crestas, agujas y geometría polar:
 */
export const RAINBOW_VOID_EFFECTS: EffectOption[] = [
  {
    id: 'dual_crest',
    name: 'Cresta Dual (Minimal visionOS)',
    desc: '2 crestas afiladas simétricas en ángulo cónico de precisión, líneas hairline y rebote elástico Kick.',
    tag: 'CRESTA DUAL',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'vector_spires',
    name: 'Agujas Vectoriales',
    desc: 'Picos afilados de alta tensión polar con micro-nodos radiantes en ápices.',
    tag: 'AGUJAS 2D',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'pulse_antennas',
    name: 'Antenas de Pulso',
    desc: 'Doble contorno armónico con resonancia vocal en frecuencias medias.',
    tag: 'ANTENAS',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'aero_fins',
    name: 'Aletas Aerodinámicas',
    desc: 'Aletas laterales escalonadas en los flancos con curvatura tangencial.',
    tag: 'ALETAS 2D',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'apex_prism',
    name: 'Prisma de Ápice',
    desc: 'Crestas triangulares puras con aristas de difracción óptica reflectante.',
    tag: 'PRISMA',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'harmonic_crown',
    name: 'Corona Armónica',
    desc: 'Cruz simétrica de 4 crestas perpendiculares con precisión matemática.',
    tag: 'CORONA 4C',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'hyperbolic_arcs',
    name: 'Arcos Hiperbólicos',
    desc: 'Arcos curvados con deflexión tangencial y tensión de resorte.',
    tag: 'ARCOS 2D',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'laser_needles',
    name: 'Agujas Láser Hairline',
    desc: 'Trazos ultrafinos de 0.75px con micro-destellos en percusión.',
    tag: 'LÁSER 2D',
    category: 'Minimalismo Sagrado',
  },
  {
    id: 'sphere',
    name: 'Núcleo Minimal Difuminado',
    desc: 'Aura de resplandor suave con capas de degradado radiante fluido y micro-surcos de vinilo.',
    tag: 'SPHERE 2D',
    category: 'Núcleo Minimal',
  },
  {
    id: 'spikes',
    name: 'Corona de Picos FFT Reactiva',
    desc: '48 agujas cristalinas radiales con micro-partículas brillantes disparadas por percusión.',
    tag: 'CORONA 48',
    category: 'Frecuencias & Picos',
  },
  {
    id: 'fractal',
    name: 'Mándala Sagrada Multicapa',
    desc: 'Mándala de 4 capas con pétalos oscilantes y vibración armónica reactiva.',
    tag: 'MÁNDALA 4L',
    category: 'Geometría Sagrada',
  },
  {
    id: 'wave_peaks',
    name: 'Halo de Ondas Reactivas',
    desc: 'Halo orbital alrededor del círculo con picos ondulantes que viajan con el ritmo y reaccionan al kick.',
    tag: 'HALO ONDAS',
    category: 'Crestas & Ondas',
  },
  {
    id: 'wave',
    name: 'Ondas de Frecuencia Líquida',
    desc: 'Cintas de ondas radiales moduladas fluidamente por el espectro de frecuencia.',
    tag: 'ONDAS LÍQUIDAS',
    category: 'Cintas & Ondas',
  },
  {
    id: 'torus',
    name: 'Anillo Neón Orbital',
    desc: 'Banda elíptica neón en rotación dual modulada por los tonos bajos.',
    tag: 'TOROIDE DUAL',
    category: 'Órbitas & Anillos',
  },
  {
    id: 'nebula',
    name: 'Nebulosa / Aurora Líquida',
    desc: '16 auroras de gas cósmico cromático con flujo turbulento y dispersión atmosférica.',
    tag: 'AURORA 2D',
    category: 'Efectos Atmosféricos',
  },
  {
    id: 'cloud',
    name: 'Nube Efervescente',
    desc: 'Partículas flotantes que emergen del núcleo hacia el halo exterior.',
    tag: 'ENJAMBRE 2D',
    category: 'Efectos Atmosféricos',
  },
];

export interface AtmosphereOption {
  id: BackgroundAtmosphere;
  name: string;
  desc: string;
  tag: string;
}

/**
 * Catálogo de Atmósferas y Fondos de Pantalla Completa
 * Independiente del núcleo circular, renderizado en capa z-0 con pointer-events: none.
 */
export const ATMOSPHERE_OPTIONS: AtmosphereOption[] = [
  {
    id: 'none',
    name: 'Fondo Limpio Zen (Desactivado)',
    desc: 'Negro abisal puro sin velos ni interferencias visuales.',
    tag: 'LIMPIO',
  },
  {
    id: 'sunset',
    name: 'Atardecer & Acantilado (DHONKIO)',
    desc: 'Atardecer épico con sol pulsante, silueta de acantilado y chispas flotantes.',
    tag: 'ATARDECER',
  },
  {
    id: 'rain',
    name: 'Lluvia Neón Estelar',
    desc: 'Trazos de lluvia vertical que aceleran con la energía musical.',
    tag: 'LLUVIA',
  },
  {
    id: 'sand',
    name: 'Arena de Mar (Mareas Sub)',
    desc: 'Partículas doradas y cian en corrientes sinusoidales al ritmo de sub-bajos.',
    tag: 'ARENA',
  },
  {
    id: 'stars',
    name: 'Estrellas 3D (Warp Speed)',
    desc: 'Vuelo a velocidad hiperespacial con campo estelar tridimensional reactivo.',
    tag: 'ESTRELLAS',
  },
  {
    id: 'radial_burst',
    name: 'Partículas del Núcleo (Estallido Radial)',
    desc: 'Partículas cristalinas y chispas que emergen del centro y viajan hacia afuera reactivas al bombo.',
    tag: 'ESTALLIDO',
  },
  {
    id: 'stardust_drift',
    name: 'Polvo Cósmico (Bruma Estelar)',
    desc: 'Micro-polvo estelar flotando suavemente en espirales concéntricas zen.',
    tag: 'POLVO CÓSMICO',
  },
  {
    id: 'light_beams',
    name: 'Haces Radiantes (Rayos Zen)',
    desc: 'Haces de luz volumétrica suave que emanan desde el centro con rotación armónica.',
    tag: 'HACES LUZ',
  },
  {
    id: 'quantum_waves',
    name: 'Ondas Cuánticas (Anillos Concéntricos)',
    desc: 'Anillos concéntricos ultrafinos que se expanden hacia los bordes en cada golpe de bajo.',
    tag: 'ONDAS',
  },
];


